### PR TITLE
Created using Colab

### PR DESCRIPTION
**Pull request by anjalipaliyam**
I did not finish the last part yet, where I will compare dominant crop values of the resulting data frame to the one from step 2

### CODE REVIEW

**Comment by anjalipaliyam** [comment]
Finished last part

**Review by ivanzvonkov — COMMENTED** [review]
## General Review
Awesome work, great use of pandas functionality, clean implementation!

FYI Python convention is a space after #:
`#your comment`
`# Python convention comment`
No need to change anything, just letting you know :)

## Next Step
The code looks good to me, I think some additional testing would be good so here's another file:
https://drive.google.com/file/d/1WzCBrO2r34o0F3_pYz5RtNaF-_VRYSau/view?usp=drive_link

In this round of testing please also download some images to check if the dominant crop method is yielding results that visually make sense. You can download some images by:

1. Logging into Google Cloud in Colab (use the same account you use for accessing the photos)
```
!gcloud auth login
```
2. Downloading an image from Google Cloud using gsutil (something like this):
```python
gcloud_image_path = df["input_img"].iloc[0]
```
```
!gsutil cp $gcloud_image_path .
```
Once this testing is complete, let me know and I think it'll be ready to merge.

**Comment by ivanzvonkov** [comment]
@anjalipaliyam let me know if you have a response here

**Comment by anjalipaliyam** [comment]
> @anjalipaliyam let me know if you have a response here

I tested the code on the additional file you provided, and also downloaded 3 images at the same location to see if it visually made sense. Let me know if you would like me to add/modify anything else.

**Review by ivanzvonkov — APPROVED** [review]
@anjalipaliyam thanks for doing the test!
For next time consider uploading your test results in the PR (or some other place) for posterity.

Please move your notebook file into the notebook folder and then go ahead and merge the PR!

**Pull request merged**
